In [1]:
                                 #datatype
import numpy as np
arr=np.array([1,2,3,4])
print(arr.dtype)

int32


In [3]:
import numpy as np 
arr=np.array(["apple","blackcurrent","orange"])
print(arr.dtype)

<U12


In [7]:
import numpy as np
arr=np.array([1.1,2.5,6.4])
newarr=arr.astype(int)
print(newarr)
print(newarr.dtype)

[1 2 6]
int32


In [9]:
import numpy as np
arr=np.array([1,0,8])
newarr=arr.astype(bool)
print(newarr)
print(newarr.dtype)

[ True False  True]
bool


In [11]:
import numpy as np
arr=np.array([1,2,3,4,5,6])
x=arr.copy()
arr[0]=85
print(arr)
print(x)

[85  2  3  4  5  6]
[1 2 3 4 5 6]


In [13]:
import numpy as np
arr=np.array([1,2,3,4,5,6])
z=arr.view()
arr[0]=48
print(arr)
print(z)

[48  2  3  4  5  6]
[48  2  3  4  5  6]


In [17]:
import numpy as np
arr=np.array([[1,2,3,],[5,9,7]])
print(arr.shape)

(2, 3)


In [19]:
import numpy as np
arr=np.array([1,2,3,4],ndmin=5)
print(arr)
print("shape of array :",arr.shape)

[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)
