In [3]:
 import numpy as np
arr=np.array([1,52,89,458])
print(type(arr))

<class 'numpy.ndarray'>


In [5]:
import numpy as np
arr=np.array([[1,8,9,69,789,56],[45,23,456,87,69,14]])
print(arr)

[[  1   8   9  69 789  56]
 [ 45  23 456  87  69  14]]


In [9]:
import numpy as np
arr=np.array([[[569,781,23,478,963],[485,69,47,12,100]],[[789,852,98,14,52],[876,900,800,632,410]]])
print(arr)

[[[569 781  23 478 963]
  [485  69  47  12 100]]

 [[789 852  98  14  52]
  [876 900 800 632 410]]]


In [11]:
import numpy as np
arr=np.array([[[569,781,23,478,963],[485,69,47,12,100]],[[789,852,98,14,52],[876,900,800,632,410]]])
print(arr[1,1,4])

410


In [13]:
import numpy as np
arr=np.array([[[569,781,23,478,963],[485,69,47,12,100]],[[789,852,98,14,52],[876,900,800,632,410]]])
print(arr[0,0,2])
print(arr[0,1,3])

23
12


In [19]:
import numpy as np
arr= np.array([[[569,781,23,478,963],[485,69,47,12,100]],[[789,852,98,14,52],[876,900,800,632,410]]])
newarr=arr.reshape(-1)
print(newarr)

[569 781  23 478 963 485  69  47  12 100 789 852  98  14  52 876 900 800
 632 410]
