In [1]:
                     # DOT() Function
import numpy as np
arr1=np.array([1,2,3])
arr2=np.array([2,4,6])
result=np.dot(arr1,arr2)
print(result)

28


In [3]:
                                        # Inner()Function
import numpy as np
arr1=np.array([[1,3],[5,7]])
arr2=np.array([[2,4],[6,8]])
result=np.inner(arr1,arr2)
result

array([[14, 30],
       [38, 86]])

In [5]:
                           # Outer()Function

import numpy as np
arr1=np.array([1,3,5])
arr2=np.array([2,4,6])
result=np.outer(arr1,arr2)
result

array([[ 2,  4,  6],
       [ 6, 12, 18],
       [10, 20, 30]])

In [7]:
                      #determinant
import numpy as np
arr=np.array([[1,3],[5,7]])
result=np.linalg.det(arr)
result

-7.999999999999998

In [9]:
                              #Slove() function
import numpy as np
a=np.array([[2,4],[6,8]])
b=np.array([5,6])
x=np.linalg.solve(a,b)
x

array([-2.  ,  2.25])

In [13]:
                             #Inv function
import numpy as np
array=np.array([[2,4],[6,8]])
result=np.linalg.inv(array)
result

array([[-1.  ,  0.5 ],
       [ 0.75, -0.25]])

In [15]:
import numpy as np
arra=np.array([[6,3,5],[9,2,1],[7,8,4]])
result=np.trace(arra)
result

12

In [19]:
import numpy as np
arr1=np.array([9,8,7])
arr2=np.array([6,5,4])
result=np.dot(arr1,arr2)
result

122

In [21]:
import numpy as np
arr1=np.array([8,7,5])
arr2=np.array([6,2,4])
result=np.outer(arr1,arr2)
result

array([[48, 16, 32],
       [42, 14, 28],
       [30, 10, 20]])