In [3]:
import numpy as np
arra=np.random.randint(10,51 ,size=(4,3))
print(arra)

[[36 20 38]
 [35 47 41]
 [17 33 47]
 [40 50 42]]


In [11]:
import numpy as np
arra=np.zeros((3,5))
print(arra)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [13]:
import numpy as np
arr=np.array([10,20,30,40],dtype=np.float32)
arr

array([10., 20., 30., 40.], dtype=float32)

In [15]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
newarr=arr.reshape(3,2)
print(arr.shape)
print(newarr)


(2, 3)
[[1 2]
 [3 4]
 [5 6]]


In [31]:
import numpy as np
arr=np.array([[10,20,30],[40,50,60],[70,80,90]])
arr1=arr[:1]
arr2=arr[0:2,1:3]
print(arr[1,1])
print(arr1)
print(arr2)

50
[[10 20 30]]
[[20 30]
 [50 60]]


In [33]:
import numpy as np
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr=np.vstack((arr1,arr2))
print(arr)

[[1 2 3]
 [4 5 6]]
