In [4]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [24]:
import numpy as np        # 1-dimension
arr=np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [10]:
import numpy as np     # 1-dimension to find type
arr1=np.array([5,6,8,9])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [12]:
import numpy as np    # 0-dimension
arr=np.array(42)
print(arr)

42


In [14]:
import numpy as np                 # 2-dimension
arr=np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [16]:
import numpy as np                               # 3-dimension
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [22]:
import numpy as np                          # dimension checking
arr=np.array(56)
a=np.array([82,96,75,93,100])
b=np.array([[52,89,74,65],[12,41,23,30]])
c=np.array([[[19,14,26,69],[95,59,78,71]],[[56,95,75,52],[23,58,97,63]]])
print(arr.ndim)
print(a.ndim)
print(b.ndim)
print(c.ndim)

0
1
2
3


In [26]:
                                 # array indexing  1D
import numpy as np
arr=np.array([1,2,3,4])
print(arr[1])

2


In [30]:
import numpy as np                    # 2D indexing
arr=np.array([[1,2,3],[5,6,8]])
print("3rd element on 2nd row :", arr[1,2])

3rd element on 2nd row : 8


In [34]:
                                # 3D indexing
import numpy as np
arr=np.array([[[5,6,9],[9,5,6]],[[8,6,7],[5,7,3]]])
print(arr[1,1,2])

3


In [40]:
                       # slicing
import numpy as np
arr=np.array([[1,2,3,5,4],[6,2,8,7,1]])
print(arr[1,1:4])

[2 8 7]


In [44]:
import numpy as np
arr=np.array([6,5,9,2,7,5,6,78,3,6])
print(arr[1:6])

[6 5 9 2 7 5]
