In [7]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr=arr.reshape(4,3)

In [11]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr=arr.reshape(4,3)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [15]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10])
mew=arr.reshape(2,5)
print(mew)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [17]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8])
newarr=arr.reshape(2,2,2)
print(newarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [19]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
newarr=arr.reshape(-1)
print(newarr)

[1 2 3 4 5 6]


In [21]:
import numpy as np
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr=np.concatenate((arr1,arr2))
print(arr)

[1 2 3 4 5 6]


In [35]:
import numpy as np
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])
arr=np.concatenate((arr1,arr2), axis=1)
print(arr)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [37]:
import numpy as np
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr=np.stack((arr1,arr2), axis=1)
print(arr)

[[1 4]
 [2 5]
 [3 6]]


In [39]:
import numpy as np
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr=np.hstack((arr1,arr2))
print(arr)

[1 2 3 4 5 6]


In [41]:
import numpy as np
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr=np.vstack((arr1,arr2))
print(arr)

[[1 2 3]
 [4 5 6]]


In [45]:
import numpy as np
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr=np.dstack((arr1,arr2))
print(arr)

[[[1 4]
  [2 5]
  [3 6]]]
